### ISSUE TITLE
Logo « melts » into content on mobile

### ISSUE THREAD

**Issue by doamatto** [doamatto/doamatto.xyz#143]
![F253ACE5-9467-4F93-99E2-57CACB396B46](https://user-images.githubusercontent.com/30969346/115818344-68ef8a80-a3b1-11eb-9d9f-ded16cce3147.png)

**Comment by yashsehgal** [comment]
Hey, @doamatto Can I work on this issue?

**Comment by doamatto** [comment]
Go for it @yashsehgal. Let me know if you need any help :)

**Comment by yashsehgal** [comment]
I think that we can solve this issue in 2 ways -
**1. We create a media query that will remove the logo from the header section once getting into the mobile view. (But that's not a good choice)** 
OR
**2. We can shift the logo to the center of the header - Above the header options.**

**Comment by doamatto** [comment]
Shifting the logo would be the most logical option; it might be solved with #145 (stopped seeing the issue then locally), but you can still take a crack at it.
